# SITE CONFIGURATION
title: Welcome to my website. # your site title
author: Ziyuan He # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://neilhzy.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Ziyuan He
  links:
#    - https://twitter.com/BenBalter
#    - https://www.facebook.com/ben.balter
    - www.linkedin.com/in/ziyuanhe
    - https://www.researchgate.net/profile/Ziyuan_He
    - https://github.com/Neilhzy


# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'CV', link: '/_pages'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Immunologist by training, data scientist in heart.

hero_img: posts/charts-computer-data-669615.jpg/ # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: zihe@ucdavis.edu # email for form submission

# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  neilhzy # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

# disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
